package com.mobileagent.host

object NativeToolCatalog {
    private val descriptorsByName: Map<String, NativeToolDescriptor> = (
        NativeSystemToolCatalog.descriptors +
        NativePlanningToolCatalog.descriptors +
        NativeDiagnosticsToolCatalog.descriptors +
        NativeWebToolCatalog.descriptors +
        NativeRecoveryToolCatalog.descriptors +
        NativeWorkspaceToolCatalog.descriptors +
        NativeSkillToolCatalog.descriptors +
        NativePluginToolCatalog.descriptors +
        NativePhoneToolCatalog.descriptors +
        NativeMcpToolCatalog.descriptors +
        NativeSshToolCatalog.descriptors +
        NativeMemoryToolCatalog.descriptors +
        NativeTerminalToolCatalog.descriptors
    ).associateBy { it.name }

    val descriptors: List<NativeToolDescriptor> = listOf(
        "get_time",
        "task_plan_update",
        "task_plan_status",
        "task_create",
        "task_list",
        "task_update",
        "task_log_append",
        "task_artifact_write",
        "task_reports",
        "task_report_read",
        "task_report_summarize",
        "task_failure_latest",
        "tool_registry",
        "tool_info",
        "toolset_request",
        "docs_index",
        "docs_read",
        "docs_search",
        "docs_sync",
        "system_logs",
        "self_health_check",
        "diagnose_terminal",
        "web_search",
        "web_extract",
        "http_get",
        "http_post",
        "recover_terminal_backend",
        "workspace_info",
        "list_files",
        "read_file",
        "write_file",
        "workspace_history",
        "workspace_restore",
        "skill_list",
        "skill_read",
        "skill_run",
        "plugin_info",
        "plugin_list",
        "plugin_create",
        "plugin_read",
        "plugin_reports",
        "plugin_report_read",
        "plugin_validate",
        "plugin_test",
        "plugin_run",
        "plugin_set_enabled",
        "search_files",
        "host_status",
        "accessibility_snapshot_v2",
        "host_screen_find",
        "host_current_app",
        "host_open_app",
        "host_click_text",
        "host_click_view_id",
        "host_click_index",
        "host_long_press_text",
        "host_long_press_index",
        "host_input_text",
        "host_clear_text",
        "host_press_key",
        "host_scroll",
        "host_swipe_coords",
        "host_wait_ms",
        "host_wait_for_text",
        "host_open_url",
        "intent_open",
        "share_file",
        "open_file_with",
        "mcp_servers",
        "mcp_status",
        "mcp_tools",
        "mcp_tool_info",
        "mcp_call",
        "mcp_configure",
        "pc_bridge_status",
        "pc_bridge_recover",
        "ssh_status",
        "ssh_diagnose",
        "ssh_select_host",
        "tailscale_preflight",
        "tailscale_ssh_diagnose",
        "ssh_connect",
        "ssh_run",
        "ssh_forward_status",
        "ssh_forward_start",
        "ssh_forward_stop",
        "ssh_disconnect",
        "file_push",
        "file_pull",
        "pc_file_workflow",
        "storage_permission_status",
        "storage_permission_open_settings",
        "memory_query",
        "memory_search",
        "memory_summary",
        "memory_write",
        "experience_search",
        "experience_record",
        "experience_update",
        "experience_delete",
        "experience_compact",
        "procedure_search",
        "procedure_generate",
        "procedure_read",
        "procedure_list",
        "learning_start",
        "learning_record",
        "learning_stop",
        "learning_status",
        "termux_status",
        "termux_tools",
        "termux_chat",
        "terminal_run",
        "terminal_script",
        "terminal_task_status",
        "terminal_task_cancel"
    ).mapNotNull { descriptorsByName[it] }
}
